# Simple Spread Testing

## Standard Simple Spread (Collaborative Only)

Agent observations: `[self_vel, self_pos, landmark_rel_positions, other_agent_rel_positions, communication]`
 - `self_vel = (2, )`
 - `self_pos = (2, )`
 - `landmark_rel_positions = (2 * N, )`
 - `other_agent_rel_positions = (2 * (N - 1), )`
 - `communication = (2 * (N - 1), )`

Agent action space: `[no_action, move_left, move_right, move_down, move_up] = (0-4)` 

In [3]:
from pettingzoo.mpe import simple_spread_v3

In [2]:
env = simple_spread_v3.parallel_env(N=5)
observations, infos = env.reset()
observations, infos


({'agent_0': array([ 0.        ,  0.        ,  0.6048849 , -0.28739527, -1.4096578 ,
          0.270138  , -0.55914074,  1.2643002 , -1.3505151 ,  0.00312318,
         -0.73575705, -0.6072447 , -0.21943055, -0.1808943 ,  0.06576544,
          0.04157067, -0.6578076 ,  0.33087328, -0.9477666 ,  0.3502272 ,
         -0.04701285, -0.21415704,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        dtype=float32),
  'agent_1': array([ 0.        ,  0.        ,  0.67065036, -0.24582459, -1.4754233 ,
          0.22856732, -0.6249062 ,  1.2227296 , -1.4162806 , -0.0384475 ,
         -0.8015225 , -0.64881533, -0.285196  , -0.22246498, -0.06576544,
         -0.04157067, -0.723573  ,  0.2893026 , -1.013532  ,  0.3086565 ,
         -0.11277829, -0.2557277 ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        dtype=float32),
  'agent_2': array([ 0.        ,  0.    

In [3]:
env.num_agents

5

In [4]:
env.state()

array([ 0.        ,  0.        ,  0.6048849 , -0.28739527, -1.4096578 ,
        0.270138  , -0.55914074,  1.2643002 , -1.3505151 ,  0.00312318,
       -0.73575705, -0.6072447 , -0.21943055, -0.1808943 ,  0.06576544,
        0.04157067, -0.6578076 ,  0.33087328, -0.9477666 ,  0.3502272 ,
       -0.04701285, -0.21415704,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.67065036, -0.24582459, -1.4754233 ,
        0.22856732, -0.6249062 ,  1.2227296 , -1.4162806 , -0.0384475 ,
       -0.8015225 , -0.64881533, -0.285196  , -0.22246498, -0.06576544,
       -0.04157067, -0.723573  ,  0.2893026 , -1.013532  ,  0.3086565 ,
       -0.11277829, -0.2557277 ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.05292263,  0.04347802, -0.7518503 ,
       -0.06073529,  0.09866682,  0.9334269 , -0.6927076 , -0.32

In [5]:
print(observations["agent_0"].shape)
observations["agent_0"]

(30,)


array([ 0.        ,  0.        ,  0.6048849 , -0.28739527, -1.4096578 ,
        0.270138  , -0.55914074,  1.2643002 , -1.3505151 ,  0.00312318,
       -0.73575705, -0.6072447 , -0.21943055, -0.1808943 ,  0.06576544,
        0.04157067, -0.6578076 ,  0.33087328, -0.9477666 ,  0.3502272 ,
       -0.04701285, -0.21415704,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
      dtype=float32)

In [6]:
env.action_space("agent_0")

Discrete(5)

In [7]:
# this is where you would insert your policy
# actions = {agent: env.action_space(agent).sample() for agent in env.agents}
actions = {agent: 0 for agent in env.agents}
observations, rewards, terminations, truncations, infos = env.step(actions)
observations, rewards, terminations, truncations, infos

({'agent_0': array([-1.7050802 , -0.3985713 ,  0.6048849 , -0.28739527, -1.4096578 ,
          0.270138  , -0.55914074,  1.2643002 , -1.3505151 ,  0.00312318,
         -0.73575705, -0.6072447 , -0.21943055, -0.1808943 ,  0.06576544,
          0.04157067, -0.6578076 ,  0.33087328, -0.9477666 ,  0.3502272 ,
         -0.04701285, -0.21415704,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        dtype=float32),
  'agent_1': array([ 1.9609631 ,  1.3748716 ,  0.67065036, -0.24582459, -1.4754233 ,
          0.22856732, -0.6249062 ,  1.2227296 , -1.4162806 , -0.0384475 ,
         -0.8015225 , -0.64881533, -0.285196  , -0.22246498, -0.06576544,
         -0.04157067, -0.723573  ,  0.2893026 , -1.013532  ,  0.3086565 ,
         -0.11277829, -0.2557277 ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        dtype=float32),
  'agent_2': array([ 0.09375016, -0.0062

## Adversarial Variant (Custom)

Agent observations: `[self_is_adversary, self_vel, self_pos, landmark_rel_positions, other_agent_is_adversary_rel_positions]`
 - `self_is_adversary = (1, )`: 0 / 1 flag
 - `self_vel = (2, )`
 - `self_pos = (2, )`
 - `landmark_rel_positions = (2 * n_landmarks, )`
 - `other_agent_is_adversary_rel_positions = ((1 + 2) * (n_agents + n_adversaries - 1), )`: 0 / 1 flag  for if that other agent is an adversary + relative position for the other agent times the number of other agents

Agent action space: `[no_action, move_left, move_right, move_down, move_up] = (0-4)` 

In [8]:
%load_ext autoreload
%autoreload 2

import simple_spread_adversarial

In [9]:
env = simple_spread_adversarial.parallel_env(n_agents=2, n_adversaries=2, n_landmarks=2)
observations, infos = env.reset()
observations, infos

({'adversary_0': array([ 1.        ,  0.        ,  0.        ,  0.71991843,  0.26426274,
         -0.1886216 ,  0.1167082 ,  0.03999711,  0.66545284,  1.        ,
         -1.709574  , -0.96413887,  0.        , -1.6893606 , -0.29679307,
          0.        , -0.70062536, -0.05053777], dtype=float32),
  'adversary_1': array([ 1.        ,  0.        ,  0.        , -0.98965555, -0.6998761 ,
          1.5209525 ,  1.080847  ,  1.7495711 ,  1.6295917 ,  1.        ,
          1.709574  ,  0.96413887,  0.        ,  0.02021344,  0.66734576,
          0.        ,  1.0089487 ,  0.9136011 ], dtype=float32),
  'agent_0': array([ 0.        ,  0.        ,  0.        , -0.9694421 , -0.03253032,
          1.500739  ,  0.41350126,  1.7293577 ,  0.96224594,  1.        ,
          1.6893606 ,  0.29679307,  1.        , -0.02021344, -0.66734576,
          0.        ,  0.9887352 ,  0.2462553 ], dtype=float32),
  'agent_1': array([ 0.        ,  0.        ,  0.        ,  0.01929311,  0.21372497,
          0.5

In [10]:
env.num_agents, env.agents

(4, ['adversary_0', 'adversary_1', 'agent_0', 'agent_1'])

In [11]:
env.state()

array([ 1.        ,  0.        ,  0.        ,  0.71991843,  0.26426274,
       -0.1886216 ,  0.1167082 ,  0.03999711,  0.66545284,  1.        ,
       -1.709574  , -0.96413887,  0.        , -1.6893606 , -0.29679307,
        0.        , -0.70062536, -0.05053777,  1.        ,  0.        ,
        0.        , -0.98965555, -0.6998761 ,  1.5209525 ,  1.080847  ,
        1.7495711 ,  1.6295917 ,  1.        ,  1.709574  ,  0.96413887,
        0.        ,  0.02021344,  0.66734576,  0.        ,  1.0089487 ,
        0.9136011 ,  0.        ,  0.        ,  0.        , -0.9694421 ,
       -0.03253032,  1.500739  ,  0.41350126,  1.7293577 ,  0.96224594,
        1.        ,  1.6893606 ,  0.29679307,  1.        , -0.02021344,
       -0.66734576,  0.        ,  0.9887352 ,  0.2462553 ,  0.        ,
        0.        ,  0.        ,  0.01929311,  0.21372497,  0.5120037 ,
        0.16724597,  0.74062246,  0.7159906 ,  1.        ,  0.70062536,
        0.05053777,  1.        , -1.0089487 , -0.9136011 ,  0.  

In [12]:
print(observations["agent_0"].shape)
observations["agent_0"]

(18,)


array([ 0.        ,  0.        ,  0.        , -0.9694421 , -0.03253032,
        1.500739  ,  0.41350126,  1.7293577 ,  0.96224594,  1.        ,
        1.6893606 ,  0.29679307,  1.        , -0.02021344, -0.66734576,
        0.        ,  0.9887352 ,  0.2462553 ], dtype=float32)

In [13]:
env.action_space("agent_0")

Discrete(5)

In [14]:
# this is where you would insert your policy
# actions = {agent: env.action_space(agent).sample() for agent in env.agents}
actions = {agent: env.action_space(agent).sample() for agent in env.agents}
observations, rewards, terminations, truncations, infos = env.step(actions)
observations, rewards, terminations, truncations, infos

({'adversary_0': array([ 1.        , -0.5       ,  0.        ,  0.71991843,  0.26426274,
         -0.1886216 ,  0.1167082 ,  0.03999711,  0.66545284,  1.        ,
         -1.709574  , -0.96413887,  0.        , -1.6893606 , -0.29679307,
          0.        , -0.70062536, -0.05053777], dtype=float32),
  'adversary_1': array([ 1.        ,  0.5       , -0.        , -0.98965555, -0.6998761 ,
          1.5209525 ,  1.080847  ,  1.7495711 ,  1.6295917 ,  1.        ,
          1.709574  ,  0.96413887,  0.        ,  0.02021344,  0.66734576,
          0.        ,  1.0089487 ,  0.9136011 ], dtype=float32),
  'agent_0': array([ 0.        , -0.5       ,  0.        , -0.9694421 , -0.03253032,
          1.500739  ,  0.41350126,  1.7293577 ,  0.96224594,  1.        ,
          1.6893606 ,  0.29679307,  1.        , -0.02021344, -0.66734576,
          0.        ,  0.9887352 ,  0.2462553 ], dtype=float32),
  'agent_1': array([ 0.        ,  0.5       , -0.        ,  0.01929311,  0.21372497,
          0.5

In [15]:
# Visualize full episode
env = simple_spread_adversarial.parallel_env(
    n_agents=2,
    n_adversaries=2,
    n_landmarks=3,
    render_mode="human"
)
observations, infos = env.reset()

while env.agents:
    # this is where you would insert your policy
    actions = {agent: env.action_space(agent).sample() for agent in env.agents}

    observations, rewards, terminations, truncations, infos = env.step(actions)
env.close()


# Testing Communication

In [20]:
temp = 3
env = simple_spread_v3.parallel_env(N=temp)
observations, infos = env.reset()
observations, infos

({'agent_0': array([ 0.        ,  0.        , -0.38328615,  0.86822903,  0.80571675,
         -0.17507046, -0.04091149, -0.4079286 ,  0.2609769 , -1.1527708 ,
          0.8894034 , -1.8245099 ,  1.0836629 , -0.5118992 ,  0.        ,
          0.        ,  0.        ,  0.        ], dtype=float32),
  'agent_1': array([ 0.        ,  0.        ,  0.5061172 , -0.9562809 , -0.08368663,
          1.6494395 , -0.9303149 ,  1.4165813 , -0.6284265 ,  0.67173916,
         -0.8894034 ,  1.8245099 ,  0.19425943,  1.3126107 ,  0.        ,
          0.        ,  0.        ,  0.        ], dtype=float32),
  'agent_2': array([ 0.        ,  0.        ,  0.7003767 ,  0.3563299 , -0.27794608,
          0.33682868, -1.1245743 ,  0.10397057, -0.8226859 , -0.6408716 ,
         -1.0836629 ,  0.5118992 , -0.19425943, -1.3126107 ,  0.        ,
          0.        ,  0.        ,  0.        ], dtype=float32)},
 {'agent_0': {}, 'agent_1': {}, 'agent_2': {}})

In [21]:
for agent in env.agents:
    observation = observations[agent]
    
    self_vel = observation[:2]
    self_pos = observation[2:4]
    idx = 4 + temp * 2
    landmark = observation[4:idx]
    idx2 = idx + (temp - 1) * 2
    other_pos = observation[idx:idx2]
    comms = observation[idx2:]
    
    print("self vel: ", self_vel)
    print("self pos: ", self_pos)
    print("landmarks: ", landmark)
    print("other players: ", other_pos)
    print("comms: ", comms)
    print("")

self vel:  [0. 0.]
self pos:  [-0.38328615  0.86822903]
landmarks:  [ 0.80571675 -0.17507046 -0.04091149 -0.4079286   0.2609769  -1.1527708 ]
other players:  [ 0.8894034 -1.8245099  1.0836629 -0.5118992]
comms:  [0. 0. 0. 0.]

self vel:  [0. 0.]
self pos:  [ 0.5061172 -0.9562809]
landmarks:  [-0.08368663  1.6494395  -0.9303149   1.4165813  -0.6284265   0.67173916]
other players:  [-0.8894034   1.8245099   0.19425943  1.3126107 ]
comms:  [0. 0. 0. 0.]

self vel:  [0. 0.]
self pos:  [0.7003767 0.3563299]
landmarks:  [-0.27794608  0.33682868 -1.1245743   0.10397057 -0.8226859  -0.6408716 ]
other players:  [-1.0836629   0.5118992  -0.19425943 -1.3126107 ]
comms:  [0. 0. 0. 0.]



In [ ]:
#     def observation(self, agent, world):
#         # get positions of all entities in this agent's reference frame
#         entity_pos = []
#         for entity in world.landmarks:  # world.entities:
#             entity_pos.append(entity.state.p_pos - agent.state.p_pos)
#         # communication of all other agents
#         comm = []
#         other_pos = []
#         for other in world.agents:
#             if other is agent:
#                 continue
#             comm.append(other.state.c)
#             other_pos.append(other.state.p_pos - agent.state.p_pos)
#         return np.concatenate(
#             [agent.state.p_vel] + [agent.state.p_pos] + entity_pos + other_pos + comm
#         )

Thoughts: Vary the amount of comm being transferred. By default, other pos are included outside of the comm vector. Potential Baselines: Mask landmarks / Mask other pos. Masking both doesn't make much sense as it essentially. becomes. Run on small number of iterations to learn policy. Ideas for custom defined comm vector: provide velocity of self to other agents (2 per other agent, 2N-1 like right now). alternatively, provide euclidan distance to each of the landmarks (my thinking is that it would explicitly force the agents to learn instead of learning implicitly via the reward func. The number would be N per agent). This could either be an absolute L2 distance or some binary variable. The binary variable could either be N per other agent (1 if within some parameter bound to landmark x, 0 if not) or 2 per other agent (1 if within some parameter bound to any landmark, 0 if not)